# Numpy

NumPy is a Python package that stands for ‘Numerical Python’.
It is the core library for scientific computing, 
which contains a powerful n-dimensional array object.

Single-dimensional Numpy Array

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
type(a)

Multi-dimensional Array:

In [3]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Random Array

arr1 = np.random.random((3))

In [ ]:
arr1

In [4]:
a.ndim

2

In [ ]:
arr1

# compare memory size of array and list

In [ ]:
import numpy as np
import sys
S= range(10)
print (type(S))
#print (D)
print(sys.getsizeof(5)*len(S))
 
D= np.arange(10)
print(type(D))
#print (D)
print(D.size*D.itemsize)

In [ ]:
import time
import sys
 
SIZE = 10
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
#result=[(x,y) for x,y in zip(L1,L2)]


result=[(x + y) for x,y in zip(L1,L2)] # List Comprehension

print((time.time()-start)*1000)
#print (result)
print (type(result))

start=time.time()
result= A1+A2
#print (result)
print (type(result))
print((time.time()-start)*1000)

In [ ]:
def sum1(x,y):
    print ("python")
    k = x*y
    return x + y
    

k = sum1(5,6)  
print (k)


In [ ]:
k = lambda x,y: x + y
print (k(5,6))

In [ ]:
import time
time.time()

In [ ]:
result

# ndim
Finding dimensions of array

In [1]:
import numpy as np
a = np.array([[(1,2),(4,5)]])
print(a.ndim)

3


In [ ]:
import numpy as np
a = np.array([[(1,2)]])
print(a.ndim)

In [ ]:
a

# itemsize
Byte size of each element.

In [ ]:
import numpy as np
a = np.array([(1,2,3)])
print(a.itemsize)

# dtype
Datatype of element stored in array

In [ ]:
import numpy as np
a = np.array([(1.0,2.0,3.0)])
print(a.dtype)


In [ ]:
import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)
print (a.ndim)

In [ ]:
k = np.array([(1,2)])

In [ ]:
k.ndim

In [4]:
s1 = "A a k a s h"
      0 1 2 3 4 5
s1[4]

's'

In [20]:
import numpy as np
a = np.array([('A','a','k','j'),('s','h','r','p')])
print(a)
print (a.size)
print (a.shape)
print (a.ndim)
# 2 rows and 3 columns 
# 3 rows and 2 columns

[['A' 'a' 'k' 'j']
 ['s' 'h' 'r' 'p']]
8
(2, 4)
2


In [18]:
a[2,2]

't'

In [22]:
a=a.reshape(2,2,2)
print(a)
print (a.size)
print (a.ndim)

[[['A' 'a']
  ['k' 'j']]

 [['s' 'h']
  ['r' 'p']]]
8
3


In [23]:
import numpy as np
a=np.array([('a','b',3,4),(3,4,5,6),(8,9,4,6)])
             
print(a[2,1]) # extracting element by index

[9]


In [ ]:
a

In [ ]:
a = 'python'
#     012345
a[0:3]

In [ ]:
import numpy as np
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:1,1])

In [ ]:
a

In [ ]:
import numpy as np
a=np.linspace(0,50,51)
print(a)

In [ ]:
import numpy as np
 
a= np.array([1,2,3,3])
print(a.min())
print(a.max())
print(a.sum())
print (a.mean())

In [ ]:
a= np.array([(1,2,3),(3,4,5)])

print (a)
print(a.sum(axis=1))


In [ ]:
# Square root and standard deviation
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))

In [ ]:
# addition substraction division multiplication division
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

In [ ]:
# Import `pyplot`
import matplotlib.pyplot as plt

# Initialize a Figure 
fig = plt.figure()

# Add Axes to the Figure
fig.add_axes([0,0,1,1])

In [ ]:
# Import the necessary packages and modules
import matplotlib.pyplot as plt
import numpy as np

# Create a Figure
fig = plt.figure()

# Set up Axes
ax = fig.add_subplot(111)

# Scatter the data
ax.scatter(np.linspace(0, 1, 5), np.linspace(0, 5, 5))

# Show the plot
plt.show()

In [ ]:
# Import the necessary packages and modules
import matplotlib.pyplot as plt
import numpy as np

# Prepare the data
x = np.linspace(0, 10, 100)

# Plot the data
plt.plot(x, x, label='linear')

# Add a legend
plt.legend()

# Show the plot
plt.show()